### PR TITLE
H3223 h4223 support

### PR DESCRIPTION
**Pull request by sqrdevl**
added support for H3223 and H4223

### CODE REVIEW

**Comment by oshmoun** [comment]
you should simply add the new models instead of replacing existing ones

**Comment by sqrdevl** [comment]
Sorry, that's what I meant to do

**Comment by kholk** [comment]
You are removing support for H3213 and H4213 and this is obviously not right.

Fix the PR!

**Comment by alviteri** [comment]
I remember doing a same thing on kanuti but alin decided to keep one model as per dual SIM and single sim

**Comment by alviteri** [comment]
https://github.com/sonyxperiadev/device-sony-tulip/tree/01e529118292238a77b21607d3d70d7693706ebf

Look at here how it was messed then alin cleaned it and let 2 models per type (dual/single) sim

**Comment by Voyager-USA** [comment]
Hi Jerpelea, the XA2 32GB model is in the supported list. What I don't understand why and more exclusive phone is not supported like the H4233? Is there no any way to get the AOSP on my phone?

**Comment by alviteri** [comment]
If your model is dual SIM you can use the present one in aosp in only will change model name

**Comment by Voyager-USA** [comment]
Hi Alviteri, yes my model is dual sim card and don't mind if the model name in the os is different. I haven't tried the 9 version yet because the 8.1 firmware I got in twrp error 255 constantly.

**Pull request closed without merging**
